### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by kurtismullins** [kubernetes-client/ruby#62]
Is this library abandoned? It appears there are no commits in 2 years and the example failed with Ruby 3.

**Comment by jeroennijhof** [comment]
I made a small fix which should work for Ruby 3, see: #64

**Comment by raesene** [comment]
I think the problem is that even with fixes to things like Ruby 3 compat, the APIs this makes available are wildly outdated. Looks like the API list was last updated 4 years ago, at Kubernetes 1.13. https://github.com/kubernetes-client/ruby/tree/master/kubernetes/lib/kubernetes/api

**Comment by jeroennijhof** [comment]
Totally agree, started a fork to fix the api changes and improve the code. I couldn't find any breaking api changes though, some features are missing indeed but nothing breaking. Am using the gem for a project with success. You can check it at https://github.com/clearcodewizards/kubernetes-io (k8s-io gem)

**Comment by 2rs2ts** [comment]
Based on [this comment in the `gen` repo](https://github.com/kubernetes-client/gen/issues/240#issuecomment-1507801063), I do think this official library is unmaintained, and trying to update it for newer API versions will be met with struggles. With that said, I hope that someone does take ownership of it, since the most popular third-party libraries seem clunky to configure compared to this one.
